apiVersion: v2
name: prometheus
version: 9.12.3
appVersion: 2.3.6
type: application

dependencies:
- name: kube-prometheus-stack
  version: "12.10.6"
  repository: "https://prometheus-community.github.io/helm-charts"
