apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: samba
spec:
  entryPoints:
    - sambatcp
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
      - name: samba
        port: 445
