apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 139
      targetPort: 139
      protocol: TCP
      name: smb139
    - port: 445
      targetPort: 445
      protocol: TCP
      name: smb445
    - port: 137
      targetPort: 137
      protocol: UDP
      name: nmb137
    - port: 138
      targetPort: 138
      protocol: UDP
      name: nmb138
  selector:
    {{- include "samba.selectorLabels" . | nindent 4 }}
