apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "transmission.fullname" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`transmission.rpi.local`)
      kind: Rule
      services:
      - name: {{ include "transmission.fullname" . }}
        port: 9091
