apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: http
      protocol: TCP
      name: http
    - port: 51413
      targetPort: peer-tcp
      protocol: TCP
      name: peer-tcp
    - port: 51413
      targetPort: peer-udp
      protocol: UDP
      targetPort: peer-udp
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
