- name: Download k3s binary arm
  become: yes
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-armhf
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm.txt
    dest: /usr/local/bin/k3s
    mode: 0755

- name: Copy K3s service file
  become: yes
  register: k3s_service
  template:
    src: "k3s.service.jinja"
    dest: "{{ systemd_dir }}/k3s.service"
    mode: 0755

- name: Copy uninstall script
  become: yes
  template:
    src: "k3s-uninstall.sh.jinja"
    dest: "/usr/local/bin/k3s-uninstall.sh"

- name: Copy killall script
  become: yes
  template:
    src: "k3s-killall.sh.jinja"
    dest: "/usr/local/bin/k3s-killall.sh"

- name: Enable and check K3s service
  become: yes
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ansible_ssh_user}}/.kube/config
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 by https://master-ip:6443
  become: true
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~/.kube/config
  changed_when: true

- name: Create kubectl symlink
  become: true
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  become: true
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Read node-token from master
  fetch:
    flat: true
    src: ~/.kube/config
    dest: ~/.kube/config
